Docs: cancel PR builds if there is no documentation changes
Use the new feature to cancel builds if there are not documentation changes

diff --git a/.readthedocs.yml b/.readthedocs.yml
--- a/.readthedocs.yml
+++ b/.readthedocs.yml
@@ -14,6 +14,21 @@ build:
   os: ubuntu-22.04
   tools:
     python: "3.10"
+  jobs:
+    post_checkout:
+      # https://docs.readthedocs.io/en/stable/build-customization.html#cancel-build-based-on-a-condition
+      #
+      # Cancel building pull requests when there aren't changed in the docs directory.
+      # `--quiet` exits with a 1 when there **are** changes,
+      # so we invert the logic with a !
+      #
+      # If there are no changes (exit 0) we force the command to return with 183.
+      # This is a special exit code on Read the Docs that will cancel the build immediately.
+      - |
+        if [ $READTHEDOCS_VERSION_TYPE = "external" ];
+        then
+          ! git diff --quiet origin/main -- docs/ && exit 183;
+        fi
 
 search:
   ranking:
